name: Java CI with Maven in Linux
on: 
  push:
  pull_request:
  
jobs: 
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8,11]
        include:
         - additional-maven-args: "-Pjacoco"
    
    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2 
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1 
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: mvn -f app/pom.xml clean verify
    - name: Generate JUnit Report
      run: >
        mvn -f app/pom.xml 
        surefire-report:report-only site:site -DgenerateReports=false
      if: ${{ always() }}
    - name: Archive JUnit Report 
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
       name: surefire-report-jdk-${{ matrix.java }} 
       path: '**/target/site'
